function [fitresult, gof] = createFit(U, I)
%CREATEFIT(U,I)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : U
%      Y Output: I
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Sep-2017 20:06:53


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( U, I );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, 'predobs', 0.9 );
legend( h, 'I vs. U', 'untitled fit 1' );
% Label axes
xlabel U
ylabel I
grid on


